const theme_dark = {
  "colors": {
    "accentcolor": null,
    "bookmark_text": null,
    "button_background_active": null,
    "button_background_hover": null,
    "frame": "#1c1b22",
    "frame_inactive": null,
    "icons": "rgb(251,251,254)",
    "icons_attention": null,
    "ntp_background": "#2A2A2E",
    "ntp_text": "rgb(251, 251, 254)",
    "popup": "rgb(66,65,77)",
    "popup_border": "rgb(82,82,94)",
    "popup_highlight": "rgb(43,42,51)",
    "popup_highlight_text": null,
    "popup_text": "rgb(251,251,254)",
    "sidebar": "#38383D",
    "sidebar_border": "rgba(255, 255, 255, 0.1)",
    "sidebar_highlight": null,
    "sidebar_highlight_text": null,
    "sidebar_text": "rgb(249, 249, 250)",
    "tab_background_separator": null,
    "tab_background_text": "#fbfbfe",
    "tab_line": "transparent",
    "tab_loading": null,
    "tab_selected": "rgb(66,65,77)",
    "tab_text": "rgb(251,251,254)",
    "textcolor": null,
    "toolbar": "rgb(43,42,51)",
    "toolbar_bottom_separator": "hsl(240, 5%, 5%)",
    "toolbar_field": "rgb(28,27,34)",
    "toolbar_field_border": "transparent",
    "toolbar_field_border_focus": null,
    "toolbar_field_focus": "rgb(66,65,77)",
    "toolbar_field_highlight": null,
    "toolbar_field_highlight_text": null,
    "toolbar_field_separator": null,
    "toolbar_field_text": "rgb(251,251,254)",
    "toolbar_field_text_focus": null,
    "toolbar_text": "rgb(251, 251, 254)",
    "toolbar_top_separator": "transparent",
    "toolbar_vertical_separator": null,
    "button": "rgb(43,42,51)",
    "button_hover": "rgb(82,82,94)",
    "button_active": "rgb(91,91,102)",
    "button_primary": "rgb(0, 221, 255)",
    "button_primary_hover": "rgb(128, 235, 255)",
    "button_primary_active": "rgb(170, 242, 255)",
    "button_primary_color": "rgb(43, 42, 51)",
    "error_text_color": "rgb(255, 154, 162)",
    "input_background": "#42414D",
    "input_color": "rgb(251,251,254)",
    "input_border": "#8f8f9d",
    "input_border_error": "rgb(255, 132, 138)",
    "zoom_controls": "rgb(74,74,85)",
    "autocomplete_popup_separator": "rgb(82,82,94)",
    "appmenu_update_icon_color": "#54FFBD",
    "appmenu_warning_icon_color": "#FFBD4F",
    "appmenu_info_icon_color": "#80EBFF",
    "tab_icon_overlay_stroke": "rgb(66,65,77)",
    "tab_icon_overlay_fill": "rgb(251,251,254)"
  },
  "images": null,
  "properties": {
    "additional_backgrounds_alignment": null,
    "additional_backgrounds_tiling": null,
    "panel_hover": "color-mix(in srgb, currentColor 9%, transparent)",
    "panel_active": "color-mix(in srgb, currentColor 14%, transparent)",
    "panel_active_darker": "color-mix(in srgb, currentColor 25%, transparent)",
    "toolbar_field_icon_opacity": "1"
  }
}
export default theme_dark;
